# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace  # Trims trailing whitespace
      - id: check-yaml  # Validates YAML files
        exclude: mkdocs.yml # the mkdocs config uses non-standard YAML syntax
      # - id: check-json  # Validates JSON files
      - id: check-added-large-files  # Checks for files added to the repository larger than a threshold
      - id: check-case-conflict  # Checks for files that would conflict in case-insensitive filesystems
      - id: check-merge-conflict  # Checks for files that contain merge conflict strings
        args:
          - --assume-in-merge
      # - id: detect-private-key  # Check for the existence of private keys
      #   exclude: |
      #     (?x)(
      #         ^0-create-kafka-service.md|
      #         ^devcontainer.json
      #     )$
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.41.0
    hooks:
      - id: markdownlint
